name: tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        include:
          # Primary testing: Latest Go on all platforms (time/concurrency testing)
          - go-version: '1.24'
            os: ubuntu-latest
          - go-version: '1.24'
            os: windows-latest
          - go-version: '1.24'
            os: macos-latest
          # Compatibility testing: Min supported Go on Linux only
          - go-version: '1.22'
            os: ubuntu-latest
          # Intermediate compatibility: Go 1.23 on Linux only
          - go-version: '1.23'
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod download
      
      # Build validation (cross-platform)
      - name: Build validation
        run: |
          go build ./...
          go mod tidy
          git diff --exit-code go.mod go.sum
      
      # Unit tests with race detection
      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        run: go test -v -race -coverprofile=coverage.out ./...
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: go test -v -coverprofile=coverage.out github.com/bold-minds/id
      - name: Run benchmarks
        run: go test -bench=. -benchmem ./...
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.24'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.3.1
